### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by JohnCox2211** [Berea-College-CSC-226/p01-final-project-arohasina#7]
**- Remove CRC card helper text** 

![image](https://github.com/user-attachments/assets/8214cd8c-917b-4057-81f6-6986347cc3fa)

**- Remove branch helper text**

![image](https://github.com/user-attachments/assets/ad520aa6-7e48-41b0-b88d-25f3b1fd5e3e)

- class Flashcard:
      - Think about how you will be storing your information (words, translations, sentences). 
         Are you using dictionaries, files, lists? 

- class Quiz
      - Much like with class Flashcard, think about how you will store the feedback and how 
         the information stored for this class will relate back to the other.

**Comment by Arohasina** [comment]
done
